package com.gsms.cn.mapper.authorization;

import com.gsms.cn.entity.authorization.RolePermission;
import com.gsms.cn.entity.authorization.RolePermissionExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface RolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE_PERMISSION
     *
     * @mbggenerated Mon Jan 22 10:20:04 CST 2018
     */
    int countByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE_PERMISSION
     *
     * @mbggenerated Mon Jan 22 10:20:04 CST 2018
     */
    int deleteByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE_PERMISSION
     *
     * @mbggenerated Mon Jan 22 10:20:04 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE_PERMISSION
     *
     * @mbggenerated Mon Jan 22 10:20:04 CST 2018
     */
    int insert(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE_PERMISSION
     *
     * @mbggenerated Mon Jan 22 10:20:04 CST 2018
     */
    int insertSelective(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE_PERMISSION
     *
     * @mbggenerated Mon Jan 22 10:20:04 CST 2018
     */
    List<RolePermission> selectByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE_PERMISSION
     *
     * @mbggenerated Mon Jan 22 10:20:04 CST 2018
     */
    RolePermission selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE_PERMISSION
     *
     * @mbggenerated Mon Jan 22 10:20:04 CST 2018
     */
    int updateByExampleSelective(@Param("record") RolePermission record, @Param("example") RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE_PERMISSION
     *
     * @mbggenerated Mon Jan 22 10:20:04 CST 2018
     */
    int updateByExample(@Param("record") RolePermission record, @Param("example") RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE_PERMISSION
     *
     * @mbggenerated Mon Jan 22 10:20:04 CST 2018
     */
    int updateByPrimaryKeySelective(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_ROLE_PERMISSION
     *
     * @mbggenerated Mon Jan 22 10:20:04 CST 2018
     */
    int updateByPrimaryKey(RolePermission record);
}