spring:
  profiles:
      active: o
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 1
    maxIdle: 20
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    testWhileIdle: true
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
  redis:
        database: 1
        pool:
          max-active: 8
          max-wait: 1
          max-idle: 500
          min-idle: 0
  session:
          store-type: redis

  #thymeleaf模板引擎
  thymeleaf:
    encoding: utf-8
    content-type: text/html
    mode: HTML

#mybatis
mybatis:
  mapper-locations: classpath*:/xml/**/*.xml
  type-aliases-package: com.**.entity

